plugin:
    name: 'vdomah.mailtranslatable::lang.plugin.name'
    description: 'vdomah.mailtranslatable::lang.plugin.description'
    author: Art Gek
    icon: oc-icon-envelope-square
    homepage: 'https://github.com/vdomah/oc-mailtranslatable-plugin'